# Generated by Django 4.2 on 2025-01-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_image_course_is_upcoming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='author_name')),
                ('author_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='author_title')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='author_image')),
                ('content', models.TextField(verbose_name='content')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'name', 'verbose_name_plural': 'names'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='is_popular'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_upcoming',
            field=models.BooleanField(default=False, verbose_name='is_upcoming'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
