# Generated by Django 4.2 on 2025-01-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial_delete_testimonials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255, verbose_name='customer')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='status')),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal')], max_length=20, verbose_name='payment method')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='stripe payment intent id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_de',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_fr',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_de',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_de',
            field=models.CharField(max_length=50, null=True, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_en',
            field=models.CharField(max_length=50, null=True, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='course',
            name='image_de',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='course',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='course',
            name='image_fr',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_de',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_en',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_fr',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
