# Generated by Django 4.2 on 2025-01-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment_category_name_de_category_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image_de',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image_fr',
        ),
        migrations.AddField(
            model_name='course',
            name='created_at_de',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at_fr',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='author name'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='author name'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='author name'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_title_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='author title'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='author title'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_title_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='author title'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_de',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_en',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_fr',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at_de',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at_fr',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
    ]
