# Generated by Django 4.2 on 2025-01-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_course_image_de_remove_course_image_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Attended', 'Attended')], default='Pending', max_length=50, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_at_de',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_at_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_at_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price_de',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price_fr',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='created_at_de',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='created_at_en',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='created_at_fr',
        ),
    ]
