# Generated by Django 4.2 on 2025-01-24 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_feedback_remove_course_created_at_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Classroom', 'Classroom')], default='Online', max_length=150, verbose_name='Course Mode'),
        ),
        migrations.CreateModel(
            name='EnrolledCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255, verbose_name='customer')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('postcode', models.CharField(max_length=50, verbose_name='Postcode')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.course', verbose_name='Course')),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.enrolledcustomer', verbose_name='Customer'),
        ),
    ]
