# Generated by Django 4.2 on 2025-01-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course_mode_enrolledcustomer_alter_payment_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolledcustomer',
            options={'verbose_name': 'enrolled_customer', 'verbose_name_plural': 'enrolled_customers'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
    ]
