# Generated by Django 4.2 on 2025-01-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_enrolledcustomer_options_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal')], default='', max_length=20, verbose_name='payment method'),
        ),
    ]
