# Generated by Django 4.2 on 2025-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_url_payment_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='mode',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Course Mode'),
        ),
    ]
