# Generated by Django 4.2 on 2025-06-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_category_slug_alter_category_slug_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='objectives',
            field=models.TextField(blank=True, null=True, verbose_name='objectives'),
        ),
        migrations.AddField(
            model_name='course',
            name='outlines',
            field=models.TextField(blank=True, null=True, verbose_name='outlines'),
        ),
    ]
