# Generated by Django 4.2 on 2025-06-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_course_objectives_course_outlines'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='goals',
            field=models.TextField(blank=True, null=True, verbose_name='goals'),
        ),
    ]
