# Generated by Django 4.2 on 2025-06-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_course_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='goals',
            field=models.TextField(blank=True, help_text='use comma separated items eg: Provide comprehensive knowledge in the subject area, Prepare participants for industry challenges', null=True, verbose_name='goals'),
        ),
        migrations.AlterField(
            model_name='course',
            name='objectives',
            field=models.TextField(blank=True, help_text='use comma separated items eg: Understand the fundamental concepts covered in this course, Develop skills relevant to the course subject matter', null=True, verbose_name='objectives'),
        ),
        migrations.AlterField(
            model_name='course',
            name='outlines',
            field=models.TextField(blank=True, help_text='use column and comma separated items eg: Module 1:Introduction and Fundamentals, Module 2:Core Concepts and Principles', null=True, verbose_name='outlines'),
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.course', verbose_name='course')),
            ],
        ),
    ]
