# Generated by Django 4.2 on 2025-09-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_course_goals_alter_course_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rank_id',
            field=models.IntegerField(blank=True, help_text='Rank ID to determine the order of courses', null=True, verbose_name='rank id'),
        ),
        migrations.AddField(
            model_name='course',
            name='training_format',
            field=models.CharField(choices=[('Online', 'Online'), ('Classroom', 'Classroom'), ('Executive', 'Executive'), ('Bespoke', 'Bespoke')], default='Online', max_length=150, verbose_name='Training Format'),
        ),
    ]
