# Generated by Django 4.2 on 2025-09-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_course_rank_id_course_training_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50, verbose_name='mode')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('allowed', models.BooleanField(default=True, verbose_name='allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'access_mode',
                'verbose_name_plural': 'access_modes',
            },
        ),
    ]
