# Generated by Django 4.2 on 2025-09-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_accessmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessmodel',
            options={},
        ),
    ]
